title: > #
    Charlie Bob Gordon: Digital Designer
description: > # this means to ignore newlines until "baseurl:"
    Digital designer in Suffolk with over 6 years of agency experience designing websites, mobile applications, user interfaces, printed collateral and presentations all with a user-centric and analytical approach.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cbg.design" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:categories/:title

# Build settings
markdown: kramdown

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
